server:
  port: 8888
cors:
  originPatterns: http://localhost:8080,http://localhost:4200
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/dbjsp?useTimezone=true&serverTimezone=UTC
    username: root
    password: Numsey#2023
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
      